### ISSUE TITLE
can u let me know

### ISSUE THREAD

**Issue by DiggityMan420** [marimelon/LeaveDutyCmdPlugin#1]
How do i install your plugin ive tried like everyway

**Comment by marimelon** [comment]
1. Build the dll file using Visual Studio. (or download it from [here](https://github.com/marimelon/LeaveDutyCmdPlugin/actions/runs/1051643101)).
2. Copy the dll file to devPlugins.
```
%APPDATA%\XIVLauncher\devPlugins\LeaveDutyCmd\1.0.0.0\LeaveDutyCmd.dll
```
3. Use /leaved in the game to escape from the dungeon.
(Open the contents menu, press the leave button, press yes. Skip this sequence of events.)

**This is a personal plugin and I take no responsibility for it.
Use it at your own risk.**
