### ISSUE TITLE
Your Plugin Here Looks Really Useful!!!

### ISSUE THREAD

**Issue by Rellawing** [marimelon/LeaveDutyCmdPlugin#2]
I asked SimpleTweaks to implement something like this today and stumbled on this soon after. But it feels like you're not making your plugin particularly accessible. Can you make a version that can be imported via the Custom Plugin Repositories in Dalamud? I'd adore having this command added to the game!

It's my goal to create a quick button that lets me leave duties quickly while running things just for a certain piece of gear or marks, etc.

**Comment by marimelon** [comment]
Thank you for submitting a Feature Request.
https://github.com/Caraxi/SimpleTweaksPlugin/issues/615
